# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1101b4cb092df351205e3bd15415b4f3e27608d91405bb47fbddd3b55b878bd45a0066b7db4e65089ad1f0d6f86c552ed185ff5f2953dc8b9e7835612af9279c

test:
  secret_key_base: 8e0c4c9403ce2b85efd12cf03a6448721c7453f789846e30a6a444a1ebe4d39e03943d45f174ca84bad0ee9549f6e432c41d5028696a3d90964a5beb32e4059f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
